### ISSUE TITLE
id is not increased

### ISSUE THREAD

**Issue by vuau** [lhorie/rem#1]
I'm trying to use this tool but I don't know how it work clearly
```javascript
$.ajax({
      method: 'post',
      url: 'http://rem-rest-api.herokuapp.com/api/users',
      data: JSON.stringify({
        firstName: 'test',
        lastName: 'test'
     }),
      xhrFields: {
        withCredentials: true
      }
})
```
The id in the response didn't change after many call

**Comment by lhorie** [comment]
It's because your method wasn't all upper case. I fixed it so that it's case insensitive
